Bec214 airkeeper unit tests
api3dao/airkeeper pull request #42
Opened 2022-03-17 17:52 UTC by acenolaza

I've added unit tests for all functions in the evm directory. I thought about adding tests to the handlers but then I realized that these are going to change a lot by the refactors planned for each one. ([rrp refactor](https://api3dao.atlassian.net/browse/BEC-238) and [psp with lambda invocation](https://api3dao.atlassian.net/browse/BEC-213)).

2022-03-21 09:03 UTC, vponline approved these changes
I think these look good to go :+1:  (minor changes coming with the refactoring PRs)

2022-03-21 09:03 UTC, vponline commented on src/evm/initialize-provider.test.ts
> +      baseFeeMultiplier: '2',
The gas price types will change to numbers in airnode v0.5, but these will be updated in the refactoring PRs.

2022-03-21 10:15 UTC, amarthadan requested changes
Nice work :+1:

2022-03-21 10:15 UTC, amarthadan commented on src/evm/initialize-provider.test.ts
> +  const providerUrl = 'http://localhost:8545';
Can you use the same URL?

2022-03-21 12:42 UTC, acenolaza commented on src/evm/check-conditions.test.ts
> +        Promise.resolve(null)
I'm just trying to cover these lines: https://github.com/api3dao/airkeeper/blob/bec214-airkeeper-unit-tests/src/evm/check-conditions.ts#L49-L53

Maybe `undefined` might be a more accurate return value 🤔

2022-03-21 14:57 UTC, amarthadan commented on src/evm/check-conditions.test.ts
> +        Promise.resolve(null)
I think you won't need to worry about that once you rebase :smile: That's why I didn't see what you're trying to test, I was looking at the current main :smile:

2022-03-21 16:42 UTC, acenolaza commented on src/evm/check-conditions.test.ts
> +        Promise.resolve(null)
LOL yes, after rebase these are the lines https://github.com/api3dao/airkeeper/blob/bec214-airkeeper-unit-tests/src/evm/check-conditions.ts#L53-L57 and I think the test might still apply

2022-03-22 08:37 UTC, amarthadan approved these changes

2022-03-22 11:34 UTC, merged